### ISSUE TITLE
Big Sur support

### ISSUE THREAD

**Issue by angristan** [nextdns/homebrew-tap#1]
👋 I currently get this error on Big Sur beta 8:

```
➜  ~ brew upgrade nextdns/tap/nextdns --debug --verbose
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/nextdns/homebrew-tap/nextdns.rb
Warning: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

==> Upgrading 1 outdated package:
nextdns/tap/nextdns 1.8.3 -> 1.8.4
==> Upgrading nextdns/tap/nextdns 1.8.3 -> 1.8.4
==> Downloading https://github.com/nextdns/nextdns/releases/download/v1.8.4/nextdns_1.8.4_darwin_amd64.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.0\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/nextdns/nextdns/releases/download/v1.8.4/nextdns_1.8.4_darwin_amd64.tar.gz
Already downloaded: /Users/stanislas/Library/Caches/Homebrew/downloads/2ac9a8e877ffaed08a9895ebe311c387e120f79a93b554a71d75f92b2a4cddf3--nextdns_1.8.4_darwin_amd64.tar.gz
==> Verifying 2ac9a8e877ffaed08a9895ebe311c387e120f79a93b554a71d75f92b2a4cddf3--nextdns_1.8.4_darwin_amd64.tar.gz checksum
rm /usr/local/bin/nextdns
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200927-19819-1fkimdt.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/nextdns/homebrew-tap/nextdns.rb --verbose --debug
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
ln -s ../Cellar/nextdns/1.8.3/bin/nextdns nextdns
Error: An exception occurred within a child process:
  SystemExit: exit
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:45:in `exit'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:45:in `checks'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:113:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
```

Is there something to be done on the cli or the tap, or is it a homebrew issue only? 

Thanks!

**Comment by angristan** [comment]
> Error: Your CLT does not support macOS 11.0.

I should check that before opening an issue, sorry.

**Comment by angristan** [comment]
I got it to work by installed the CLT version 12 and Xcode version 12 beta 2 from the Apple website. 

```
➜  ~ brew config
HOMEBREW_VERSION: 2.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: cd4a3c0588abb82d916bc8558f4c157e951d449d
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 12a8c88b8b6c7e6da099b0555d1d7b13fbd8c436
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2, 11.0.8
macOS: 11.0-x86_64
CLT: 12.0.0.0.1.1597368733
Xcode: 12.2 => /Applications/Xcode-beta.app/Contents/Developer
```
